# Generated by Django 2.2.8 on 2019-12-13 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('title',
                 models.CharField(max_length=256,
                                  verbose_name='Article Title')),
                ('content', models.TextField()),
                ('created_date',
                 models.DateTimeField(auto_now=True,
                                      verbose_name='publish date')),
                ('modified',
                 models.DateTimeField(auto_now=True,
                                      verbose_name='modified date')),
                ('slug',
                 models.CharField(
                     blank=True,
                     editable=False,
                     help_text=
                     'Unique URL path to access this page. Generated by the system.',
                     max_length=256)),
                ('author',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='news.Author')),
            ],
        ),
    ]
