# Generated by Django 2.2.8 on 2019-12-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousArticle',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('title',
                 models.CharField(max_length=256,
                                  verbose_name='Article Title')),
                ('content', models.TextField()),
                ('created_date',
                 models.DateTimeField(auto_now=True,
                                      verbose_name='publish date')),
                ('slug',
                 models.CharField(
                     blank=True,
                     editable=False,
                     help_text=
                     'Unique URL path to access this page. Generated by the system.',
                     max_length=256)),
            ],
        ),
    ]
